server:
  port: 8050

spring:
  application:
    name: content-center

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/content_center?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # 服务实例元数据
        metadata:
          instance: a

#        # namespace 多环境隔离
#        namespace: 369a89f7-ade4-4c06-a6d5-2cdf074f9c61
#        # 集群 多机房优先调用
#        cluster-name: CDC

# ribbon
# 开启饥饿加载(项目启动就创建实例),解决指定服务第一次请求过慢的问题
ribbon:
  eager-load:
    enabled: true
    clients: user-center

# 指定user-center服务ribbon的负载均衡策略
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule
---
spring:
  profiles: dev

---
spring:
  profiles: prod