server:
  port: 8050

spring:
  application:
    name: content-center

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/content_center?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root

  # 允许编写多个feignClient且同名
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # 服务实例元数据
        metadata:
          # 定义本服务版本
          version: v1
          # 定义调用其他服务的版本
          target-version: v1

#        # namespace 多环境隔离
#        namespace: 369a89f7-ade4-4c06-a6d5-2cdf074f9c61
        # 集群名称 多机房优先调用
        cluster-name: CDC

# ribbon
# 开启饥饿加载(项目启动就创建实例),解决指定服务第一次请求过慢的问题
ribbon:
  eager-load:
    enabled: true
    # 指定饥饿加载哪些服务
    clients: user-center

# 指定user-center服务ribbon的负载均衡策略
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule
logging:
  level:
  # 指定具体fegin的日志级别，必须配置
    com.fanyao.alibaba.contentcenter.feginclient.UserCenterFeginClient: debug
    com.fanyao.alibaba.contentcenter.feginclient.TestUserCenterFeginClient: debug

# feign指定服务的日志级别
feign:
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
        connectTimeout: 5000
        readTimeout: 5000

#      # 细粒度配置 调用服务的服务名
#      user-center:
#        loggerLevel: full


---
spring:
  profiles: dev

---
spring:
  profiles: prod