server:
  port: 8050

nacos-server-addr: localhost:8848
sentinel-server-addr:  localhost:8080

spring:
  application:
    name: content-center

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/content_center?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root

  # 允许编写多个feignClient且同名
  main:
    allow-bean-definition-overriding: true

  cloud:
    #-------------------------nacos-----------------------#
    nacos:
      discovery:
        server-addr: ${nacos-server-addr}
        # 服务实例元数据
        metadata:
          # 定义本服务版本
          version: v1
          # 定义调用其他服务的版本
          target-version: v1

        #        # namespace 多环境隔离
        #        namespace: 369a89f7-ade4-4c06-a6d5-2cdf074f9c61
        # 集群名称 多机房优先调用
        cluster-name: CDC
    #-------------------------sentinel-----------------------#
    sentinel:
      transport:
        dashboard: ${sentinel-server-addr}
      filter:
        # 打开/关闭对spring 端点保护
        enabled: true
    #---------------stream----------------#
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876

      bindings:
        output:
          destination: stream-test-topic

# ---------------------ribbon--------------------------------#
# ribbon 不支持 配置文件的全局配置
# 开启饥饿加载(项目启动就创建实例),解决指定服务第一次请求过慢的问题
ribbon:/
  eager-load:
    enabled: true
    # 指定饥饿加载哪些服务
    clients: user-center

# 指定user-center服务ribbon的负载均衡策略
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule

# ---------------------feign--------------------------------#
logging:
  level:
    # 指定具体feign的日志级别，必须配置
    com.fanyao.alibaba.contentcenter.feignclient.*: debug

# feign指定服务的日志级别
feign:
  client:
    config:
      # 全局配置
      default:
        loggerLevel: FULL
        connectTimeout: 5000
        readTimeout: 5000

  #      # 细粒度配置 调用服务的服务名
  #      user-center:
  #        loggerLevel: full
  # feign性能调整: 使用连接池 日志级别设为basic
  # 切换为http client连接方式，取消掉 默认的URLConnection
  httpclient:
    enabled: true
    # feign 最大连接数
    max-connections: 200
    # 单个端点的最大连接数 (根据压测逐步调整这两个值)
    max-connections-per-route: 50

  sentinel:
    # feign整合sentinel
    enabled: true

# ---------------------actuator--------------------------------#
management:
  endpoints:
    web:
      exposure:
        include: '*'
resttemplate:
  sentinel:
    # 关闭@SentinelRestTemplate 在开发阶段,不想起用流控和降级设置为false
    enabled: true

#------------rocketMQ--------------------#
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    # 必须写group 否则启动失败
    group: yao-group


---
spring:
  profiles: dev

---
spring:
  profiles: prod